"""cascade delete user-patient-admin-doctor2

Revision ID: 7e06e328295b
Revises: a77f0a9ce702
Create Date: 2024-12-17 15:45:13.096174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e06e328295b'
down_revision: Union[str, None] = 'a77f0a9ce702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedules_doctor_id_fkey', 'schedules', type_='foreignkey')
    op.create_foreign_key(None, 'schedules', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.create_foreign_key('schedules_doctor_id_fkey', 'schedules', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###
