"""cascade delete user-patient-admin-doctor

Revision ID: a77f0a9ce702
Revises: 8dc84444cc5a
Create Date: 2024-12-17 15:39:24.065075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77f0a9ce702'
down_revision: Union[str, None] = '8dc84444cc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_admin_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_patient_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_doctor_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'admins', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_doctor_id_fkey', 'users', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key('users_patient_id_fkey', 'users', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key('users_admin_id_fkey', 'users', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###
